name: Build

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    strategy:
      matrix:
        node-version: [12, 14, 16]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm ci 
      - name: lint
        run: npm run lint

      - name: test
        run: npm run test:ci

      - name: Coveralls Parallel
        id: coveralls-parallel
        continue-on-error: true
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel: true
          flag-name: run-${{ matrix.node-version }}-${{ matrix.os }}

      - name: Should Trigger coverallsapp/github-action@master
        id: coveralls-trigger
        # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#steps-context
        # when continue-on-error failed, outcome is failure and conclusion is success
        if: steps.coveralls-parallel.conclusion == 'success' && steps.coveralls-parallel.outcome != 'success'
        run: |
          echo "::set-output name=COVERALLS_TRIGGER::failure"

      - name: Build 
        run: npm run build

  coverage:
    needs: build
    runs-on: ubuntu-latest
    if: needs.build.outputs.COVERALLS != 'failure'
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
